audit_header: false
title: Ellis County Real Estate Video Blog with Krissy Mireles
description: Our mission at Holmquist & Associates Realty is to be your best resource for Ellis County real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Holmquist & Associates Realty, your professional Ellis County Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Krissy Mireles
  title:
  license_number:
  about_markdown: |
    My success is a result of experience, integrity, dedication and the desire for excellence! I thrive on being the industry-leader and trusted resource for my clients while delivering them the BEST customer service for all their REAL ESTATE NEEDS! Nothing gives me more satisfaction than helping buyers and sellers accomplish their goals of acquiring or disposing of real estate. I have been selling real estate for over 22 years and have a passion for this industry and helping people. I am continually staying abreast with current changes, laws, market activity, mortgage rates, marketing and top of the line negotiating skills to help you achieve your goals.
  market: Ellis County
  brand: Holmquist & Associates Realty
  brokerage:
  address:
  phone: 512-903-1121
  phone_type:
  phone2:
  phone2_type:
  email: krissy@krissym.com
  url: http://krissym.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.krissym.com/sell.php
  second_CTA_text: Home Search
  second_CTA_URL: https://www.krissym.com/index.php?rtype=grid

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Ellis County Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.krissym.com/sell.php

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Ellis County Home?"
    CTA_text2: "Search the entire MLS for your Ellis County home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.krissym.com/index.php?rtype=grid

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KrissyMirelesRealtor
  linkedin_url:
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UClMFanUqbnxssTxmbGZ-r2w
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Ellis County Real Estate Podcast with Krissy Mireles'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Ellis County Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Holmquist & Associates Realty - your professional Ellis County Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Ellis County, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Krissy Mireles'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Ellis County Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c5a95e'
  theme_color: '#1a1a1a'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
